window.WK_RELEASES = [
  {
    title: 'Come Alive',
    artist: '',
    releaseDate: '2026',
    description: 'The pulse of the desert, channelled through teal light and cosmic bass. Come Alive is DuneSurfer at full frequency.',
    coverImage: 'https://d2ol7oe51mr4n9.cloudfront.net/user_39LyNd3yWOiGeUhnS3CdfDw25su/64fd075c-58d4-4015-9a2b-50c001f03b51.png',
    previewAudio: '',
    spotifyUrl: 'https://open.spotify.com/album/3VTTWLemncJUChC2KBQXbp',
    appleMusicUrl: 'https://music.apple.com/us/album/come-alive-single/6787306452',
    youtubeUrl: 'https://www.youtube.com/watch?v=FiPeWOLsctU',
    distrokidUrl: '',
    featured: true
  },
  {
    title: 'Moksha Nova',
    artist: '',
    releaseDate: '2026',
    description: 'Sacred geometry meets psydance energy. A transcendent journey through cosmic frequencies.',
    coverImage: 'https://d2ol7oe51mr4n9.cloudfront.net/user_39LyNd3yWOiGeUhnS3CdfDw25su/b30c2018-a825-4734-ad79-aab9c52ecf5f.png',
    previewAudio: '',
    spotifyUrl: 'https://open.spotify.com/track/555V6isiXhVHNBRGu3689q',
    appleMusicUrl: 'https://music.apple.com/us/album/moksha-nova-single/6790055555',
    youtubeUrl: 'https://www.youtube.com/watch?v=GZwisKHtPKI',
    distrokidUrl: '',
    featured: false
  },
  {
    title: 'Afrikaner Girl',
    artist: 'feat. Lauren-Louise',
    releaseDate: '2026',
    description: 'Desert bass meets soulful vocals. A love letter from the dunes, built for late-night dancefloors.',
    coverImage: 'https://d2ol7oe51mr4n9.cloudfront.net/user_39LyNd3yWOiGeUhnS3CdfDw25su/568d37e4-4ae9-4c10-8173-5fe57a4f8699.png',
    previewAudio: '',
    spotifyUrl: 'https://open.spotify.com/album/71unUIO18E43eKRYrlne7q',
    appleMusicUrl: 'https://music.apple.com/us/album/afrikaner-girl/6780004932?i=6780005116',
    youtubeUrl: 'https://www.youtube.com/watch?v=t6mIc-pPB9o',
    distrokidUrl: '',
    featured: false
  },
  {
    title: 'Soul Radio',
    artist: '',
    releaseDate: '2026',
    description: 'Tune into the frequency. Psydance transmissions from another dimension.',
    coverImage: 'https://d2ol7oe51mr4n9.cloudfront.net/user_39LyNd3yWOiGeUhnS3CdfDw25su/20f08d51-3c71-4ec8-b364-c040f21e8778.png',
    previewAudio: '',
    spotifyUrl: 'https://open.spotify.com/album/3AwBol8jQkrwJRwMkSdQhw',
    appleMusicUrl: 'https://music.apple.com/us/album/soul-radio-single/6775303784',
    youtubeUrl: 'https://www.youtube.com/watch?v=gyLVbzcbSV0',
    distrokidUrl: '',
    featured: false
  },
  {
    title: 'All of Us',
    artist: 'feat. Lauren-Louise',
    releaseDate: '2025',
    description: 'Euphoric, uplifting and built for the collective. A festival anthem from the desert.',
    coverImage: 'https://d2ol7oe51mr4n9.cloudfront.net/user_39LyNd3yWOiGeUhnS3CdfDw25su/85f835a1-f869-4ded-a738-e89a9ccb9bc8.png',
    previewAudio: '',
    spotifyUrl: 'https://open.spotify.com/album/38n0I2rlczdl4CL9CkRptf',
    appleMusicUrl: 'https://music.apple.com/us/album/all-of-us-single/6769236707',
    youtubeUrl: 'https://www.youtube.com/watch?v=UbuF8zzSmNI',
    distrokidUrl: '',
    featured: false
  },
  {
    title: 'Our Hearts Beat',
    artist: 'feat. Lauren-Louise',
    releaseDate: '2025',
    description: 'Where heartbeat meets bassline. An emotional psydance journey through city lights and desert nights.',
    coverImage: 'https://d2ol7oe51mr4n9.cloudfront.net/user_39LyNd3yWOiGeUhnS3CdfDw25su/23360c4b-c60b-4013-85cd-055d9407a15e.png',
    previewAudio: '',
    spotifyUrl: 'https://open.spotify.com/album/7D7RpiJtyn5F3DRleuRUCW',
    appleMusicUrl: 'https://music.apple.com/us/album/our-hearts-beat-single/6768122919',
    youtubeUrl: 'https://www.youtube.com/watch?v=Mg2usChdlkY',
    distrokidUrl: '',
    featured: false
  }
];
